name: fxtm_forex_tracker
description: A Flutter app for tracking real-time forex prices and historical data.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^0.13.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  web_socket_channel: ^2.4.0
  flutter_dotenv: ^5.2.1
  charts_flutter: ^0.12.0
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  mockito: ^5.4.2
  bloc_test: ^9.1.3
  http: ^0.13.6
  mocktail: ^1.0.3  # Mock API and Bloc behavior
  connectivity_plus: ^5.0.2



flutter:
  uses-material-design: true
  assets:
    - .env
